### ISSUE TITLE
Claim Interest button not working

### ISSUE THREAD

**Issue by regnar1** [KomodoPlatform/agama-mobile#15]
It's been a recent thing (maybe Mobile hasn't updated since May 1st) but when I try to claim interest (blue claim button>Green claim X KMD interest button) it registers with "verifying transaction data..." for a second or two then disappears and nothing happens afterwards. 

I think this may be an issue with the app searching a bad explorer for transaction info.

**Comment by pbca26** [comment]
closing, likely not relevant anylonger
