### ISSUE TITLE
Cannot Login or Add coin

### ISSUE THREAD

**Issue by CW-YenNQ** [KomodoPlatform/agama-mobile#20]
Reproduce steps:
1. Open app, wait for splashscreen
2. Sign In screen appears, but instead of login form (or something like that), it displays coin list ([img](https://photos.app.goo.gl/9J9xDhc2j4jKyfd16))
3. Touch any coin in the list, no reaction
4. Click on the side menu, can see the Add coin & Create seed appear ([img](https://photos.app.goo.gl/UbJupufz57RVAaqQ7))
5. Click Add coin, the coin list appears but similar to 3. no reaction on touch

Device info:
- Samsung Galaxy S8+
- Android version: 8.0.0

**Comment by pbca26** [comment]
please try v0.1.1

**Comment by CW-YenNQ** [comment]
Works like a charm~
