### ISSUE TITLE
Misleading info on sign in

### ISSUE THREAD

**Issue by passcombo** [KomodoPlatform/agama-mobile#30]
"Create a PIN to sign in". It's not required to sign in, so I call it misleading, some users may actually abandon the page at that moment.

Some adjustment needed, more in "steps" (I do not mean steps like new screens, can be just explained in new lines on the same screen - best):

1. Type seed or WIF to sign in (in place of "create PIN to sign in")
2. [optional but suggested for new users] Create PIN for this WIF/seed for faster wallet opening. You will be able to type PIN on this device to faster load the WIF/seed assigned to it. You can have multiple PINs assigned to multiple WIFs/seeds.

PS might be worth to consider Mycelium login experience on mobile. They already got many users, so their way might be some way popular? Or at least tested on thousands of users? Just to consider if it might be better/faster.

**Comment by pbca26** [comment]
login/create wallet is completely refactored in 0.1.5
