### ISSUE TITLE
ERC20: Send Transaction details shows my eth balance on Android

### ISSUE THREAD

**Issue by Nagaws** [KomodoPlatform/agama-mobile#42]
Tried sending some funds from erc20 coin,  Current balance and balance after fee shows incorrectly it shows my eth balance.

Is this correct behaviour ?

https://www.screencast.com/t/HKll8EMq5CF

**Comment by pbca26** [comment]
i've changed wording a bit
does it make the info on that screen any better?

**Comment by Nagaws** [comment]
It looks better now on new build. Thanks for addressing this small detail :-)
