### ISSUE TITLE
Transactions list showing incomplete information Android Samsung Galaxy J1 Mini Prime

### ISSUE THREAD

**Issue by Hermes08** [KomodoPlatform/agama-mobile#43]
Display issue with Samsung Galaxy  J1 Mini Prime model SM J106B

Android Version 6.0.1

![whatsapp image 2018-11-21 at 3 38 38 pm](https://user-images.githubusercontent.com/42009518/48870297-53c03d00-edae-11e8-954a-2c1597fc6231.jpeg)

**Comment by pbca26** [comment]
closing
