### ISSUE TITLE
Agama Pirate z-tx shown as public in tx history

### ISSUE THREAD

**Issue by passcombo** [KomodoPlatform/agama-mobile#46]
I see this in native Pirate wallet z-tx next to each tx history:

https://imgur.com/a/cDAXg6n

**Comment by passcombo** [comment]
Version 3.1d Full window pic: https://imgur.com/a/sVe7tV2

**Comment by pbca26** [comment]
this is a wrong repo
please repost your issue here https://github.com/KomodoPlatform/Agama
