### ISSUE TITLE
Auto retry connect to electrum server

### ISSUE THREAD

**Issue by pbca26** [KomodoPlatform/agama-mobile#48]

**Comment by ca333** [comment]
@pbca26 can we please fix the below issue - it seems this is one of the major issues affecting endusers. I guess we have to "(check spv server before connecting and) auto re-connect & switch SPV server in case of connection-error". 

![ima_1f7d39b](https://user-images.githubusercontent.com/10762374/52473017-0f666100-2b95-11e9-834d-08cd8d3fb79f.png)

**Comment by pbca26** [comment]
closing, fixed in 0.1.5
