### ISSUE TITLE
Please use another bitcoin fees API provider

### ISSUE THREAD

**Issue by bretton** [KomodoPlatform/agama-mobile#65]
Hi, I'm not familiar with your project. I did a search for `https://bitcoinfees.earn.com/api/v1/fees/recommended` and am alerting projects using this API to inaccurate & old data.

An up-to-date API with accurate data would be `https://mempool.space/api/v1/fees/recommended` or some alternative.

https://github.com/KomodoPlatform/agama-mobile/blob/c48ade579be5186280f3b8b7968dc43bab432b7a/imports/ui/actions/actions.js

**Comment by gcharang** [comment]
thanks for letting us know. This project is deprecated.
