### ISSUE TITLE
Startup screen 

### ISSUE THREAD

**Issue by Erlix322** [KomodoPlatform/agama-mobile#7]
Hi,
It is not really a bug but I've noticed that when I start the App there is some kind of distracting startup screen in there(see screenshot) :

https://drive.google.com/file/d/1hh4Zy9AdBJb3CENwYqasxxT6mw_IOSG6/view?usp=drivesdk

Oh and could you make the 'button clicked' effect on the pin input a bit more visible? When i first typed the pin I thought it was not responding to my input.

**Comment by pbca26** [comment]
this issue was already fixed in newer verison
